name: build protodep

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: 1.22.6

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make test
      - run: make build-all




